version: 0.0
os: linux

files:
  - source: /
    destination: /start.py

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_flask_app.sh
      timeout: 300
      runas: root
