version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: migrate.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
